INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Exploding Kittens", "Board Game", 10000, "1/1/2015", "2/19/2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Golem", "Blockchain", 8600000, "11/11/2016", "11/11/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ouya", "Video Game", 950000, "7/1/2012", "8/9/2012");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Shenmue III", "Video Game", 2000000, "7/16/2015", "Ongoing");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("FirstBlood Crowdsale", "Software", 5500000, "9/26/2016", "9/26/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pono Music", "Computing Hardware", 800000, "4/1/2014", "4/15/2014");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mayday PAC", "Other", 6000000, "5/1/2014", "7/4/2014");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fidget Cube", "Other", 15000, "10/15/2016", "10/19/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Veronica Mars", "Movie", 2000000, "4/1/2013", "4/13/2013");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Lisk", "Software", NULL, "2/29/2016", "3/21/2016");

INSERT INTO users (name, age) VALUES ("Jill Johns",35);
INSERT INTO users (name, age) VALUES ("Jill Johnson",25);
INSERT INTO users (name, age) VALUES ("John Johnsson",42);
INSERT INTO users (name, age) VALUES ("Jenna Josephs",18);
INSERT INTO users (name, age) VALUES ("Joseph Jackson",54);
INSERT INTO users (name, age) VALUES ("Jackson Jones",17);
INSERT INTO users (name, age) VALUES ("Jezebel Jones",62);
INSERT INTO users (name, age) VALUES ("Jemimah Johnson",30);
INSERT INTO users (name, age) VALUES ("Jack Jacobs",29);
INSERT INTO users (name, age) VALUES ("Jeremiah Jacobsen",38);
INSERT INTO users (name, age) VALUES ("Jerry Johansen",44);
INSERT INTO users (name, age) VALUES ("Jason Jeremy",45);
INSERT INTO users (name, age) VALUES ("Jeremy Jason",58);
INSERT INTO users (name, age) VALUES ("Janet Jacks",21);
INSERT INTO users (name, age) VALUES ("Joline Jones",27);
INSERT INTO users (name, age) VALUES ("Jenny Jetson",59);
INSERT INTO users (name, age) VALUES ("Jane Jansen",49);
INSERT INTO users (name, age) VALUES ("Jojo Jones",60);
INSERT INTO users (name, age) VALUES ("James Jamieson",51);
INSERT INTO users (name, age) VALUES ("Jenny Jacobson",40);
