INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Exploding Kittens", "Board Game", 10000, "1/1/2015", "2/19/2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Golem", "Blockchain", 8600000, "11/11/2016", "11/11/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ouya", "Video Game", 950000, "7/1/2012", "8/9/2012");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Shenmue III", "Video Game", 2000000, "7/16/2015", "Ongoing");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("FirstBlood Crowdsale", "Software", 5500000, "9/26/2016", "9/26/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pono Music", "Computing Hardware", 800000, "4/1/2014", "4/15/2014");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mayday PAC", "Other", 6000000, "5/1/2014", "7/4/2014");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fidget Cube", "Other", 15000, "10/15/2016", "10/19/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Veronica Mars", "Movie", 2000000, "4/1/2013", "4/13/2013");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Lisk", "Software", NULL, "2/29/2016", "3/21/2016");

INSERT INTO users (name, age) VALUES ("Jill Johns",35);
INSERT INTO users (name, age) VALUES ("Jill Johnson",25);
INSERT INTO users (name, age) VALUES ("John Johnsson",42);
INSERT INTO users (name, age) VALUES ("Jenna Josephs",18);
INSERT INTO users (name, age) VALUES ("Joseph Jackson",54);
INSERT INTO users (name, age) VALUES ("Jackson Jones",17);
INSERT INTO users (name, age) VALUES ("Jezebel Jones",62);
INSERT INTO users (name, age) VALUES ("Jemimah Johnson",30);
INSERT INTO users (name, age) VALUES ("Jack Jacobs",29);
INSERT INTO users (name, age) VALUES ("Jeremiah Jacobsen",38);
INSERT INTO users (name, age) VALUES ("Jerry Johansen",44);
INSERT INTO users (name, age) VALUES ("Jason Jeremy",45);
INSERT INTO users (name, age) VALUES ("Jeremy Jason",58);
INSERT INTO users (name, age) VALUES ("Janet Jacks",21);
INSERT INTO users (name, age) VALUES ("Joline Jones",27);
INSERT INTO users (name, age) VALUES ("Jenny Jetson",59);
INSERT INTO users (name, age) VALUES ("Jane Jansen",49);
INSERT INTO users (name, age) VALUES ("Jojo Jones",60);
INSERT INTO users (name, age) VALUES ("James Jamieson",51);
INSERT INTO users (name, age) VALUES ("Jenny Jacobson",40);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10000,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,2,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,3,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,4,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250000,5,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,6,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,7,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20000,7,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500,8,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,9,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,9,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100000,10,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,10,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000,11,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000,11,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25000,12,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250000,12,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500,13,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,13,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100000,14,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000,14,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6500,14,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12500,15,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500,16,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,17,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7500,17,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120000,18,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000000,19,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000,20,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15000,20,3);
